#!/bin/bash

# Only output instructions when running in Claude Code on the web
if [ "$CLAUDE_CODE_REMOTE" != "true" ]; then
  exit 0
fi

cat << 'EOF'
### CI/CD

GitHub Actions runs E2E tests on every PR (`.github/workflows/e2e-tests.yml`).
After pushing, use `gh pr checks --watch` to wait for CI without burning tokens.

## Claude Code on the web Workflow

When running in **Claude Code on the web** (not CLI):

**MANDATORY: Always create a PR and verify E2E tests pass before considering work complete.**

- **DO NOT push directly to `main`** — use session branch only
- Push all changes to the assigned session branch (e.g., `claude/feature-name-<session-id>`)
- **ALWAYS create a PR** for any code changes - this triggers CI/CD pipeline
- **ALWAYS wait for E2E tests** to pass using `gh pr checks --watch`
- The wiki submodule (`Sviter-wiki/`) can be pushed to main directly since it's a separate repo

### Required Workflow

1. Push changes to session branch: `git push -u origin claude/feature-SESSION_ID`
2. Create PR: `gh pr create --title "..." --body "..."`
3. Wait for E2E tests: `gh pr checks --watch --fail-fast`
4. If tests fail: fix, commit, push, repeat step 3
5. When E2E tests pass, check claude-review comments: `gh pr view --comments`
6. Fix issues marked as High Priority / Fix before merge, then consider work complete

```bash
# NOTE: Always use --repo flag (remote URL is proxied, gh can't detect repo)
# Replace "honix/Sviter" with actual repo if different

# 1. Push changes to session branch
git push -u origin claude/your-feature-SESSION_ID

# 2. Create PR (triggers CI)
# IMPORTANT: Always be transparent - mention in PR body that this was generated by Claude
gh pr create --repo honix/Sviter --title "feat: ..." --body "..."

# 3. Wait for "E2E Tests" job only (ignore claude-review while fixing)
gh pr checks --repo honix/Sviter --watch --fail-fast

# 4. If E2E Tests failed, check logs and fix
gh run view --repo honix/Sviter --log-failed

# 5. Fix and push again, repeat until E2E Tests green
git add . && git commit -m "fix: ..." && git push

# 6. When E2E Tests green, wait for claude-review then read its feedback
gh pr checks --repo honix/Sviter --watch
gh pr view --repo honix/Sviter --comments
# Fix issues marked as High Priority / Fix before merge - other suggestions can be ignored
```
EOF
